// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBtAJwCTuHTBEOH-F6uPxKKbwi-gKYnIw',
    appId: '1:334917663328:web:6c0cabc15bbb8223796105',
    messagingSenderId: '334917663328',
    projectId: 'maan-room-booking-app',
    authDomain: 'maan-room-booking-app.firebaseapp.com',
    storageBucket: 'maan-room-booking-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdQaDkFPsgZb9bH13cxFuVgTyhIPLGQxQ',
    appId: '1:334917663328:android:8459a04900f78456796105',
    messagingSenderId: '334917663328',
    projectId: 'maan-room-booking-app',
    storageBucket: 'maan-room-booking-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDhiWAEjTY8V4IC7VdJWA24JDBJ1Sq78o',
    appId: '1:334917663328:ios:05e9022609fd5ede796105',
    messagingSenderId: '334917663328',
    projectId: 'maan-room-booking-app',
    storageBucket: 'maan-room-booking-app.appspot.com',
    iosBundleId: 'dev.maan.roomBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDhiWAEjTY8V4IC7VdJWA24JDBJ1Sq78o',
    appId: '1:334917663328:ios:05e9022609fd5ede796105',
    messagingSenderId: '334917663328',
    projectId: 'maan-room-booking-app',
    storageBucket: 'maan-room-booking-app.appspot.com',
    iosBundleId: 'dev.maan.roomBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBtAJwCTuHTBEOH-F6uPxKKbwi-gKYnIw',
    appId: '1:334917663328:web:6717fb2ba8f1b27e796105',
    messagingSenderId: '334917663328',
    projectId: 'maan-room-booking-app',
    authDomain: 'maan-room-booking-app.firebaseapp.com',
    storageBucket: 'maan-room-booking-app.appspot.com',
  );
}
